<?php
/**
 * CustomersApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Devdraft\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Devdraft\ApiException;
use Devdraft\Configuration;
use Devdraft\FormDataProcessor;
use Devdraft\HeaderSelector;
use Devdraft\ObjectSerializer;

/**
 * CustomersApi Class Doc Comment
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'customerControllerCreate' => [
            'application/json',
        ],
        'customerControllerFindAll' => [
            'application/json',
        ],
        'customerControllerFindOne' => [
            'application/json',
        ],
        'customerControllerUpdate' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation customerControllerCreate
     *
     * Create a new customer
     *
     * @param  \Devdraft\Model\CreateCustomerDto $create_customer_dto Customer creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerCreate'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function customerControllerCreate($create_customer_dto, string $contentType = self::contentTypes['customerControllerCreate'][0])
    {
        $this->customerControllerCreateWithHttpInfo($create_customer_dto, $contentType);
    }

    /**
     * Operation customerControllerCreateWithHttpInfo
     *
     * Create a new customer
     *
     * @param  \Devdraft\Model\CreateCustomerDto $create_customer_dto Customer creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerCreate'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function customerControllerCreateWithHttpInfo($create_customer_dto, string $contentType = self::contentTypes['customerControllerCreate'][0])
    {
        $request = $this->customerControllerCreateRequest($create_customer_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation customerControllerCreateAsync
     *
     * Create a new customer
     *
     * @param  \Devdraft\Model\CreateCustomerDto $create_customer_dto Customer creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerControllerCreateAsync($create_customer_dto, string $contentType = self::contentTypes['customerControllerCreate'][0])
    {
        return $this->customerControllerCreateAsyncWithHttpInfo($create_customer_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation customerControllerCreateAsyncWithHttpInfo
     *
     * Create a new customer
     *
     * @param  \Devdraft\Model\CreateCustomerDto $create_customer_dto Customer creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerControllerCreateAsyncWithHttpInfo($create_customer_dto, string $contentType = self::contentTypes['customerControllerCreate'][0])
    {
        $returnType = '';
        $request = $this->customerControllerCreateRequest($create_customer_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'customerControllerCreate'
     *
     * @param  \Devdraft\Model\CreateCustomerDto $create_customer_dto Customer creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function customerControllerCreateRequest($create_customer_dto, string $contentType = self::contentTypes['customerControllerCreate'][0])
    {

        // verify the required parameter 'create_customer_dto' is set
        if ($create_customer_dto === null || (is_array($create_customer_dto) && count($create_customer_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_customer_dto when calling customerControllerCreate'
            );
        }


        $resourcePath = '/api/v0/customers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_customer_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_customer_dto));
            } else {
                $httpBody = $create_customer_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation customerControllerFindAll
     *
     * Get all customers with filters
     *
     * @param  float|null $skip Number of records to skip for pagination (optional, default to 0)
     * @param  float|null $take Number of records to return (max 100) (optional, default to 10)
     * @param  \Devdraft\Model\CustomerStatus|null $status Filter customers by status (optional)
     * @param  string|null $name Filter customers by name (partial match, case-insensitive) (optional)
     * @param  string|null $email Filter customers by email (exact match, case-insensitive) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerFindAll'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function customerControllerFindAll($skip = 0, $take = 10, $status = null, $name = null, $email = null, string $contentType = self::contentTypes['customerControllerFindAll'][0])
    {
        $this->customerControllerFindAllWithHttpInfo($skip, $take, $status, $name, $email, $contentType);
    }

    /**
     * Operation customerControllerFindAllWithHttpInfo
     *
     * Get all customers with filters
     *
     * @param  float|null $skip Number of records to skip for pagination (optional, default to 0)
     * @param  float|null $take Number of records to return (max 100) (optional, default to 10)
     * @param  \Devdraft\Model\CustomerStatus|null $status Filter customers by status (optional)
     * @param  string|null $name Filter customers by name (partial match, case-insensitive) (optional)
     * @param  string|null $email Filter customers by email (exact match, case-insensitive) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerFindAll'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function customerControllerFindAllWithHttpInfo($skip = 0, $take = 10, $status = null, $name = null, $email = null, string $contentType = self::contentTypes['customerControllerFindAll'][0])
    {
        $request = $this->customerControllerFindAllRequest($skip, $take, $status, $name, $email, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation customerControllerFindAllAsync
     *
     * Get all customers with filters
     *
     * @param  float|null $skip Number of records to skip for pagination (optional, default to 0)
     * @param  float|null $take Number of records to return (max 100) (optional, default to 10)
     * @param  \Devdraft\Model\CustomerStatus|null $status Filter customers by status (optional)
     * @param  string|null $name Filter customers by name (partial match, case-insensitive) (optional)
     * @param  string|null $email Filter customers by email (exact match, case-insensitive) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerFindAll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerControllerFindAllAsync($skip = 0, $take = 10, $status = null, $name = null, $email = null, string $contentType = self::contentTypes['customerControllerFindAll'][0])
    {
        return $this->customerControllerFindAllAsyncWithHttpInfo($skip, $take, $status, $name, $email, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation customerControllerFindAllAsyncWithHttpInfo
     *
     * Get all customers with filters
     *
     * @param  float|null $skip Number of records to skip for pagination (optional, default to 0)
     * @param  float|null $take Number of records to return (max 100) (optional, default to 10)
     * @param  \Devdraft\Model\CustomerStatus|null $status Filter customers by status (optional)
     * @param  string|null $name Filter customers by name (partial match, case-insensitive) (optional)
     * @param  string|null $email Filter customers by email (exact match, case-insensitive) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerFindAll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerControllerFindAllAsyncWithHttpInfo($skip = 0, $take = 10, $status = null, $name = null, $email = null, string $contentType = self::contentTypes['customerControllerFindAll'][0])
    {
        $returnType = '';
        $request = $this->customerControllerFindAllRequest($skip, $take, $status, $name, $email, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'customerControllerFindAll'
     *
     * @param  float|null $skip Number of records to skip for pagination (optional, default to 0)
     * @param  float|null $take Number of records to return (max 100) (optional, default to 10)
     * @param  \Devdraft\Model\CustomerStatus|null $status Filter customers by status (optional)
     * @param  string|null $name Filter customers by name (partial match, case-insensitive) (optional)
     * @param  string|null $email Filter customers by email (exact match, case-insensitive) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerFindAll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function customerControllerFindAllRequest($skip = 0, $take = 10, $status = null, $name = null, $email = null, string $contentType = self::contentTypes['customerControllerFindAll'][0])
    {

        if ($skip !== null && $skip < 0) {
            throw new \InvalidArgumentException('invalid value for "$skip" when calling CustomersApi.customerControllerFindAll, must be bigger than or equal to 0.');
        }
        
        if ($take !== null && $take > 100) {
            throw new \InvalidArgumentException('invalid value for "$take" when calling CustomersApi.customerControllerFindAll, must be smaller than or equal to 100.');
        }
        if ($take !== null && $take < 1) {
            throw new \InvalidArgumentException('invalid value for "$take" when calling CustomersApi.customerControllerFindAll, must be bigger than or equal to 1.');
        }
        

        if ($name !== null && strlen($name) > 100) {
            throw new \InvalidArgumentException('invalid length for "$name" when calling CustomersApi.customerControllerFindAll, must be smaller than or equal to 100.');
        }
        
        if ($email !== null && strlen($email) > 255) {
            throw new \InvalidArgumentException('invalid length for "$email" when calling CustomersApi.customerControllerFindAll, must be smaller than or equal to 255.');
        }
        

        $resourcePath = '/api/v0/customers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            'skip', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $take,
            'take', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'CustomerStatus', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name,
            'name', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $email,
            'email', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation customerControllerFindOne
     *
     * Get a customer by ID
     *
     * @param  string $id Customer unique identifier (UUID) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerFindOne'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function customerControllerFindOne($id, string $contentType = self::contentTypes['customerControllerFindOne'][0])
    {
        $this->customerControllerFindOneWithHttpInfo($id, $contentType);
    }

    /**
     * Operation customerControllerFindOneWithHttpInfo
     *
     * Get a customer by ID
     *
     * @param  string $id Customer unique identifier (UUID) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerFindOne'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function customerControllerFindOneWithHttpInfo($id, string $contentType = self::contentTypes['customerControllerFindOne'][0])
    {
        $request = $this->customerControllerFindOneRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation customerControllerFindOneAsync
     *
     * Get a customer by ID
     *
     * @param  string $id Customer unique identifier (UUID) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerFindOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerControllerFindOneAsync($id, string $contentType = self::contentTypes['customerControllerFindOne'][0])
    {
        return $this->customerControllerFindOneAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation customerControllerFindOneAsyncWithHttpInfo
     *
     * Get a customer by ID
     *
     * @param  string $id Customer unique identifier (UUID) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerFindOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerControllerFindOneAsyncWithHttpInfo($id, string $contentType = self::contentTypes['customerControllerFindOne'][0])
    {
        $returnType = '';
        $request = $this->customerControllerFindOneRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'customerControllerFindOne'
     *
     * @param  string $id Customer unique identifier (UUID) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerFindOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function customerControllerFindOneRequest($id, string $contentType = self::contentTypes['customerControllerFindOne'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling customerControllerFindOne'
            );
        }


        $resourcePath = '/api/v0/customers/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation customerControllerUpdate
     *
     * Update a customer
     *
     * @param  string $id Customer unique identifier (UUID) (required)
     * @param  \Devdraft\Model\UpdateCustomerDto $update_customer_dto Customer update data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerUpdate'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function customerControllerUpdate($id, $update_customer_dto, string $contentType = self::contentTypes['customerControllerUpdate'][0])
    {
        $this->customerControllerUpdateWithHttpInfo($id, $update_customer_dto, $contentType);
    }

    /**
     * Operation customerControllerUpdateWithHttpInfo
     *
     * Update a customer
     *
     * @param  string $id Customer unique identifier (UUID) (required)
     * @param  \Devdraft\Model\UpdateCustomerDto $update_customer_dto Customer update data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerUpdate'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function customerControllerUpdateWithHttpInfo($id, $update_customer_dto, string $contentType = self::contentTypes['customerControllerUpdate'][0])
    {
        $request = $this->customerControllerUpdateRequest($id, $update_customer_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation customerControllerUpdateAsync
     *
     * Update a customer
     *
     * @param  string $id Customer unique identifier (UUID) (required)
     * @param  \Devdraft\Model\UpdateCustomerDto $update_customer_dto Customer update data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerControllerUpdateAsync($id, $update_customer_dto, string $contentType = self::contentTypes['customerControllerUpdate'][0])
    {
        return $this->customerControllerUpdateAsyncWithHttpInfo($id, $update_customer_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation customerControllerUpdateAsyncWithHttpInfo
     *
     * Update a customer
     *
     * @param  string $id Customer unique identifier (UUID) (required)
     * @param  \Devdraft\Model\UpdateCustomerDto $update_customer_dto Customer update data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function customerControllerUpdateAsyncWithHttpInfo($id, $update_customer_dto, string $contentType = self::contentTypes['customerControllerUpdate'][0])
    {
        $returnType = '';
        $request = $this->customerControllerUpdateRequest($id, $update_customer_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'customerControllerUpdate'
     *
     * @param  string $id Customer unique identifier (UUID) (required)
     * @param  \Devdraft\Model\UpdateCustomerDto $update_customer_dto Customer update data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['customerControllerUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function customerControllerUpdateRequest($id, $update_customer_dto, string $contentType = self::contentTypes['customerControllerUpdate'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling customerControllerUpdate'
            );
        }

        // verify the required parameter 'update_customer_dto' is set
        if ($update_customer_dto === null || (is_array($update_customer_dto) && count($update_customer_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_customer_dto when calling customerControllerUpdate'
            );
        }


        $resourcePath = '/api/v0/customers/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_customer_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_customer_dto));
            } else {
                $httpBody = $update_customer_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
