<?php
/**
 * InvoicesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Devdraft\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Devdraft\ApiException;
use Devdraft\Configuration;
use Devdraft\FormDataProcessor;
use Devdraft\HeaderSelector;
use Devdraft\ObjectSerializer;

/**
 * InvoicesApi Class Doc Comment
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoicesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'invoiceControllerCreate' => [
            'application/json',
        ],
        'invoiceControllerFindAll' => [
            'application/json',
        ],
        'invoiceControllerFindOne' => [
            'application/json',
        ],
        'invoiceControllerUpdate' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation invoiceControllerCreate
     *
     * Create a new invoice
     *
     * @param  \Devdraft\Model\CreateInvoiceDto $create_invoice_dto create_invoice_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerCreate'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function invoiceControllerCreate($create_invoice_dto, string $contentType = self::contentTypes['invoiceControllerCreate'][0])
    {
        $this->invoiceControllerCreateWithHttpInfo($create_invoice_dto, $contentType);
    }

    /**
     * Operation invoiceControllerCreateWithHttpInfo
     *
     * Create a new invoice
     *
     * @param  \Devdraft\Model\CreateInvoiceDto $create_invoice_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerCreate'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function invoiceControllerCreateWithHttpInfo($create_invoice_dto, string $contentType = self::contentTypes['invoiceControllerCreate'][0])
    {
        $request = $this->invoiceControllerCreateRequest($create_invoice_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation invoiceControllerCreateAsync
     *
     * Create a new invoice
     *
     * @param  \Devdraft\Model\CreateInvoiceDto $create_invoice_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoiceControllerCreateAsync($create_invoice_dto, string $contentType = self::contentTypes['invoiceControllerCreate'][0])
    {
        return $this->invoiceControllerCreateAsyncWithHttpInfo($create_invoice_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoiceControllerCreateAsyncWithHttpInfo
     *
     * Create a new invoice
     *
     * @param  \Devdraft\Model\CreateInvoiceDto $create_invoice_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoiceControllerCreateAsyncWithHttpInfo($create_invoice_dto, string $contentType = self::contentTypes['invoiceControllerCreate'][0])
    {
        $returnType = '';
        $request = $this->invoiceControllerCreateRequest($create_invoice_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoiceControllerCreate'
     *
     * @param  \Devdraft\Model\CreateInvoiceDto $create_invoice_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function invoiceControllerCreateRequest($create_invoice_dto, string $contentType = self::contentTypes['invoiceControllerCreate'][0])
    {

        // verify the required parameter 'create_invoice_dto' is set
        if ($create_invoice_dto === null || (is_array($create_invoice_dto) && count($create_invoice_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_invoice_dto when calling invoiceControllerCreate'
            );
        }


        $resourcePath = '/api/v0/invoices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_invoice_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_invoice_dto));
            } else {
                $httpBody = $create_invoice_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation invoiceControllerFindAll
     *
     * Get all invoices
     *
     * @param  float|null $skip Number of records to skip (optional)
     * @param  float|null $take Number of records to take (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerFindAll'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function invoiceControllerFindAll($skip = null, $take = null, string $contentType = self::contentTypes['invoiceControllerFindAll'][0])
    {
        $this->invoiceControllerFindAllWithHttpInfo($skip, $take, $contentType);
    }

    /**
     * Operation invoiceControllerFindAllWithHttpInfo
     *
     * Get all invoices
     *
     * @param  float|null $skip Number of records to skip (optional)
     * @param  float|null $take Number of records to take (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerFindAll'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function invoiceControllerFindAllWithHttpInfo($skip = null, $take = null, string $contentType = self::contentTypes['invoiceControllerFindAll'][0])
    {
        $request = $this->invoiceControllerFindAllRequest($skip, $take, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation invoiceControllerFindAllAsync
     *
     * Get all invoices
     *
     * @param  float|null $skip Number of records to skip (optional)
     * @param  float|null $take Number of records to take (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerFindAll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoiceControllerFindAllAsync($skip = null, $take = null, string $contentType = self::contentTypes['invoiceControllerFindAll'][0])
    {
        return $this->invoiceControllerFindAllAsyncWithHttpInfo($skip, $take, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoiceControllerFindAllAsyncWithHttpInfo
     *
     * Get all invoices
     *
     * @param  float|null $skip Number of records to skip (optional)
     * @param  float|null $take Number of records to take (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerFindAll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoiceControllerFindAllAsyncWithHttpInfo($skip = null, $take = null, string $contentType = self::contentTypes['invoiceControllerFindAll'][0])
    {
        $returnType = '';
        $request = $this->invoiceControllerFindAllRequest($skip, $take, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoiceControllerFindAll'
     *
     * @param  float|null $skip Number of records to skip (optional)
     * @param  float|null $take Number of records to take (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerFindAll'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function invoiceControllerFindAllRequest($skip = null, $take = null, string $contentType = self::contentTypes['invoiceControllerFindAll'][0])
    {




        $resourcePath = '/api/v0/invoices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $skip,
            'skip', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $take,
            'take', // param base name
            'number', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation invoiceControllerFindOne
     *
     * Get an invoice by ID
     *
     * @param  string $id Invoice ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerFindOne'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function invoiceControllerFindOne($id, string $contentType = self::contentTypes['invoiceControllerFindOne'][0])
    {
        $this->invoiceControllerFindOneWithHttpInfo($id, $contentType);
    }

    /**
     * Operation invoiceControllerFindOneWithHttpInfo
     *
     * Get an invoice by ID
     *
     * @param  string $id Invoice ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerFindOne'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function invoiceControllerFindOneWithHttpInfo($id, string $contentType = self::contentTypes['invoiceControllerFindOne'][0])
    {
        $request = $this->invoiceControllerFindOneRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation invoiceControllerFindOneAsync
     *
     * Get an invoice by ID
     *
     * @param  string $id Invoice ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerFindOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoiceControllerFindOneAsync($id, string $contentType = self::contentTypes['invoiceControllerFindOne'][0])
    {
        return $this->invoiceControllerFindOneAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoiceControllerFindOneAsyncWithHttpInfo
     *
     * Get an invoice by ID
     *
     * @param  string $id Invoice ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerFindOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoiceControllerFindOneAsyncWithHttpInfo($id, string $contentType = self::contentTypes['invoiceControllerFindOne'][0])
    {
        $returnType = '';
        $request = $this->invoiceControllerFindOneRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoiceControllerFindOne'
     *
     * @param  string $id Invoice ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerFindOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function invoiceControllerFindOneRequest($id, string $contentType = self::contentTypes['invoiceControllerFindOne'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling invoiceControllerFindOne'
            );
        }


        $resourcePath = '/api/v0/invoices/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation invoiceControllerUpdate
     *
     * Update an invoice
     *
     * @param  string $id Invoice ID (required)
     * @param  \Devdraft\Model\CreateInvoiceDto $create_invoice_dto create_invoice_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerUpdate'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function invoiceControllerUpdate($id, $create_invoice_dto, string $contentType = self::contentTypes['invoiceControllerUpdate'][0])
    {
        $this->invoiceControllerUpdateWithHttpInfo($id, $create_invoice_dto, $contentType);
    }

    /**
     * Operation invoiceControllerUpdateWithHttpInfo
     *
     * Update an invoice
     *
     * @param  string $id Invoice ID (required)
     * @param  \Devdraft\Model\CreateInvoiceDto $create_invoice_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerUpdate'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function invoiceControllerUpdateWithHttpInfo($id, $create_invoice_dto, string $contentType = self::contentTypes['invoiceControllerUpdate'][0])
    {
        $request = $this->invoiceControllerUpdateRequest($id, $create_invoice_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation invoiceControllerUpdateAsync
     *
     * Update an invoice
     *
     * @param  string $id Invoice ID (required)
     * @param  \Devdraft\Model\CreateInvoiceDto $create_invoice_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoiceControllerUpdateAsync($id, $create_invoice_dto, string $contentType = self::contentTypes['invoiceControllerUpdate'][0])
    {
        return $this->invoiceControllerUpdateAsyncWithHttpInfo($id, $create_invoice_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoiceControllerUpdateAsyncWithHttpInfo
     *
     * Update an invoice
     *
     * @param  string $id Invoice ID (required)
     * @param  \Devdraft\Model\CreateInvoiceDto $create_invoice_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoiceControllerUpdateAsyncWithHttpInfo($id, $create_invoice_dto, string $contentType = self::contentTypes['invoiceControllerUpdate'][0])
    {
        $returnType = '';
        $request = $this->invoiceControllerUpdateRequest($id, $create_invoice_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoiceControllerUpdate'
     *
     * @param  string $id Invoice ID (required)
     * @param  \Devdraft\Model\CreateInvoiceDto $create_invoice_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoiceControllerUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function invoiceControllerUpdateRequest($id, $create_invoice_dto, string $contentType = self::contentTypes['invoiceControllerUpdate'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling invoiceControllerUpdate'
            );
        }

        // verify the required parameter 'create_invoice_dto' is set
        if ($create_invoice_dto === null || (is_array($create_invoice_dto) && count($create_invoice_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_invoice_dto when calling invoiceControllerUpdate'
            );
        }


        $resourcePath = '/api/v0/invoices/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_invoice_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_invoice_dto));
            } else {
                $httpBody = $create_invoice_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
