<?php
/**
 * LiquidationAddressesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Devdraft\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Devdraft\ApiException;
use Devdraft\Configuration;
use Devdraft\FormDataProcessor;
use Devdraft\HeaderSelector;
use Devdraft\ObjectSerializer;

/**
 * LiquidationAddressesApi Class Doc Comment
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LiquidationAddressesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'liquidationAddressControllerCreateLiquidationAddress' => [
            'application/json',
        ],
        'liquidationAddressControllerGetLiquidationAddress' => [
            'application/json',
        ],
        'liquidationAddressControllerGetLiquidationAddresses' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation liquidationAddressControllerCreateLiquidationAddress
     *
     * Create a new liquidation address for a customer
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  \Devdraft\Model\CreateLiquidationAddressDto $create_liquidation_address_dto create_liquidation_address_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerCreateLiquidationAddress'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Devdraft\Model\LiquidationAddressResponseDto|mixed|mixed|mixed
     */
    public function liquidationAddressControllerCreateLiquidationAddress($customer_id, $create_liquidation_address_dto, string $contentType = self::contentTypes['liquidationAddressControllerCreateLiquidationAddress'][0])
    {
        list($response) = $this->liquidationAddressControllerCreateLiquidationAddressWithHttpInfo($customer_id, $create_liquidation_address_dto, $contentType);
        return $response;
    }

    /**
     * Operation liquidationAddressControllerCreateLiquidationAddressWithHttpInfo
     *
     * Create a new liquidation address for a customer
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  \Devdraft\Model\CreateLiquidationAddressDto $create_liquidation_address_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerCreateLiquidationAddress'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Devdraft\Model\LiquidationAddressResponseDto|mixed|mixed|mixed, HTTP status code, HTTP response headers (array of strings)
     */
    public function liquidationAddressControllerCreateLiquidationAddressWithHttpInfo($customer_id, $create_liquidation_address_dto, string $contentType = self::contentTypes['liquidationAddressControllerCreateLiquidationAddress'][0])
    {
        $request = $this->liquidationAddressControllerCreateLiquidationAddressRequest($customer_id, $create_liquidation_address_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Devdraft\Model\LiquidationAddressResponseDto',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Devdraft\Model\LiquidationAddressResponseDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Devdraft\Model\LiquidationAddressResponseDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation liquidationAddressControllerCreateLiquidationAddressAsync
     *
     * Create a new liquidation address for a customer
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  \Devdraft\Model\CreateLiquidationAddressDto $create_liquidation_address_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerCreateLiquidationAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function liquidationAddressControllerCreateLiquidationAddressAsync($customer_id, $create_liquidation_address_dto, string $contentType = self::contentTypes['liquidationAddressControllerCreateLiquidationAddress'][0])
    {
        return $this->liquidationAddressControllerCreateLiquidationAddressAsyncWithHttpInfo($customer_id, $create_liquidation_address_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation liquidationAddressControllerCreateLiquidationAddressAsyncWithHttpInfo
     *
     * Create a new liquidation address for a customer
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  \Devdraft\Model\CreateLiquidationAddressDto $create_liquidation_address_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerCreateLiquidationAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function liquidationAddressControllerCreateLiquidationAddressAsyncWithHttpInfo($customer_id, $create_liquidation_address_dto, string $contentType = self::contentTypes['liquidationAddressControllerCreateLiquidationAddress'][0])
    {
        $returnType = '\Devdraft\Model\LiquidationAddressResponseDto';
        $request = $this->liquidationAddressControllerCreateLiquidationAddressRequest($customer_id, $create_liquidation_address_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'liquidationAddressControllerCreateLiquidationAddress'
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  \Devdraft\Model\CreateLiquidationAddressDto $create_liquidation_address_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerCreateLiquidationAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function liquidationAddressControllerCreateLiquidationAddressRequest($customer_id, $create_liquidation_address_dto, string $contentType = self::contentTypes['liquidationAddressControllerCreateLiquidationAddress'][0])
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null || (is_array($customer_id) && count($customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_id when calling liquidationAddressControllerCreateLiquidationAddress'
            );
        }

        // verify the required parameter 'create_liquidation_address_dto' is set
        if ($create_liquidation_address_dto === null || (is_array($create_liquidation_address_dto) && count($create_liquidation_address_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_liquidation_address_dto when calling liquidationAddressControllerCreateLiquidationAddress'
            );
        }


        $resourcePath = '/api/v0/customers/{customerId}/liquidation_addresses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'customerId' . '}',
                ObjectSerializer::toPathValue($customer_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_liquidation_address_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_liquidation_address_dto));
            } else {
                $httpBody = $create_liquidation_address_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation liquidationAddressControllerGetLiquidationAddress
     *
     * Get a specific liquidation address
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  string $liquidation_address_id Unique identifier for the liquidation address (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerGetLiquidationAddress'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Devdraft\Model\LiquidationAddressResponseDto|mixed|mixed
     */
    public function liquidationAddressControllerGetLiquidationAddress($customer_id, $liquidation_address_id, string $contentType = self::contentTypes['liquidationAddressControllerGetLiquidationAddress'][0])
    {
        list($response) = $this->liquidationAddressControllerGetLiquidationAddressWithHttpInfo($customer_id, $liquidation_address_id, $contentType);
        return $response;
    }

    /**
     * Operation liquidationAddressControllerGetLiquidationAddressWithHttpInfo
     *
     * Get a specific liquidation address
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  string $liquidation_address_id Unique identifier for the liquidation address (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerGetLiquidationAddress'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Devdraft\Model\LiquidationAddressResponseDto|mixed|mixed, HTTP status code, HTTP response headers (array of strings)
     */
    public function liquidationAddressControllerGetLiquidationAddressWithHttpInfo($customer_id, $liquidation_address_id, string $contentType = self::contentTypes['liquidationAddressControllerGetLiquidationAddress'][0])
    {
        $request = $this->liquidationAddressControllerGetLiquidationAddressRequest($customer_id, $liquidation_address_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Devdraft\Model\LiquidationAddressResponseDto',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Devdraft\Model\LiquidationAddressResponseDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Devdraft\Model\LiquidationAddressResponseDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation liquidationAddressControllerGetLiquidationAddressAsync
     *
     * Get a specific liquidation address
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  string $liquidation_address_id Unique identifier for the liquidation address (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerGetLiquidationAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function liquidationAddressControllerGetLiquidationAddressAsync($customer_id, $liquidation_address_id, string $contentType = self::contentTypes['liquidationAddressControllerGetLiquidationAddress'][0])
    {
        return $this->liquidationAddressControllerGetLiquidationAddressAsyncWithHttpInfo($customer_id, $liquidation_address_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation liquidationAddressControllerGetLiquidationAddressAsyncWithHttpInfo
     *
     * Get a specific liquidation address
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  string $liquidation_address_id Unique identifier for the liquidation address (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerGetLiquidationAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function liquidationAddressControllerGetLiquidationAddressAsyncWithHttpInfo($customer_id, $liquidation_address_id, string $contentType = self::contentTypes['liquidationAddressControllerGetLiquidationAddress'][0])
    {
        $returnType = '\Devdraft\Model\LiquidationAddressResponseDto';
        $request = $this->liquidationAddressControllerGetLiquidationAddressRequest($customer_id, $liquidation_address_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'liquidationAddressControllerGetLiquidationAddress'
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  string $liquidation_address_id Unique identifier for the liquidation address (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerGetLiquidationAddress'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function liquidationAddressControllerGetLiquidationAddressRequest($customer_id, $liquidation_address_id, string $contentType = self::contentTypes['liquidationAddressControllerGetLiquidationAddress'][0])
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null || (is_array($customer_id) && count($customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_id when calling liquidationAddressControllerGetLiquidationAddress'
            );
        }

        // verify the required parameter 'liquidation_address_id' is set
        if ($liquidation_address_id === null || (is_array($liquidation_address_id) && count($liquidation_address_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $liquidation_address_id when calling liquidationAddressControllerGetLiquidationAddress'
            );
        }


        $resourcePath = '/api/v0/customers/{customerId}/liquidation_addresses/{liquidationAddressId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'customerId' . '}',
                ObjectSerializer::toPathValue($customer_id),
                $resourcePath
            );
        }
        // path params
        if ($liquidation_address_id !== null) {
            $resourcePath = str_replace(
                '{' . 'liquidationAddressId' . '}',
                ObjectSerializer::toPathValue($liquidation_address_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation liquidationAddressControllerGetLiquidationAddresses
     *
     * Get all liquidation addresses for a customer
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerGetLiquidationAddresses'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Devdraft\Model\LiquidationAddressResponseDto[]|mixed|mixed
     */
    public function liquidationAddressControllerGetLiquidationAddresses($customer_id, string $contentType = self::contentTypes['liquidationAddressControllerGetLiquidationAddresses'][0])
    {
        list($response) = $this->liquidationAddressControllerGetLiquidationAddressesWithHttpInfo($customer_id, $contentType);
        return $response;
    }

    /**
     * Operation liquidationAddressControllerGetLiquidationAddressesWithHttpInfo
     *
     * Get all liquidation addresses for a customer
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerGetLiquidationAddresses'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Devdraft\Model\LiquidationAddressResponseDto[]|mixed|mixed, HTTP status code, HTTP response headers (array of strings)
     */
    public function liquidationAddressControllerGetLiquidationAddressesWithHttpInfo($customer_id, string $contentType = self::contentTypes['liquidationAddressControllerGetLiquidationAddresses'][0])
    {
        $request = $this->liquidationAddressControllerGetLiquidationAddressesRequest($customer_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Devdraft\Model\LiquidationAddressResponseDto[]',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        'mixed',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Devdraft\Model\LiquidationAddressResponseDto[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Devdraft\Model\LiquidationAddressResponseDto[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'mixed',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation liquidationAddressControllerGetLiquidationAddressesAsync
     *
     * Get all liquidation addresses for a customer
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerGetLiquidationAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function liquidationAddressControllerGetLiquidationAddressesAsync($customer_id, string $contentType = self::contentTypes['liquidationAddressControllerGetLiquidationAddresses'][0])
    {
        return $this->liquidationAddressControllerGetLiquidationAddressesAsyncWithHttpInfo($customer_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation liquidationAddressControllerGetLiquidationAddressesAsyncWithHttpInfo
     *
     * Get all liquidation addresses for a customer
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerGetLiquidationAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function liquidationAddressControllerGetLiquidationAddressesAsyncWithHttpInfo($customer_id, string $contentType = self::contentTypes['liquidationAddressControllerGetLiquidationAddresses'][0])
    {
        $returnType = '\Devdraft\Model\LiquidationAddressResponseDto[]';
        $request = $this->liquidationAddressControllerGetLiquidationAddressesRequest($customer_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'liquidationAddressControllerGetLiquidationAddresses'
     *
     * @param  string $customer_id Unique identifier for the customer (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['liquidationAddressControllerGetLiquidationAddresses'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function liquidationAddressControllerGetLiquidationAddressesRequest($customer_id, string $contentType = self::contentTypes['liquidationAddressControllerGetLiquidationAddresses'][0])
    {

        // verify the required parameter 'customer_id' is set
        if ($customer_id === null || (is_array($customer_id) && count($customer_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $customer_id when calling liquidationAddressControllerGetLiquidationAddresses'
            );
        }


        $resourcePath = '/api/v0/customers/{customerId}/liquidation_addresses';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($customer_id !== null) {
            $resourcePath = str_replace(
                '{' . 'customerId' . '}',
                ObjectSerializer::toPathValue($customer_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
