<?php
/**
 * PaymentIntentsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Devdraft\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Devdraft\ApiException;
use Devdraft\Configuration;
use Devdraft\FormDataProcessor;
use Devdraft\HeaderSelector;
use Devdraft\ObjectSerializer;

/**
 * PaymentIntentsApi Class Doc Comment
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentIntentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'paymentIntentControllerCreateBankPaymentIntent' => [
            'application/json',
        ],
        'paymentIntentControllerCreateStablePaymentIntent' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation paymentIntentControllerCreateBankPaymentIntent
     *
     * Create a bank payment intent
     *
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     * @param  \Devdraft\Model\CreateBankPaymentIntentDto $create_bank_payment_intent_dto Bank payment intent creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentIntentControllerCreateBankPaymentIntent'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function paymentIntentControllerCreateBankPaymentIntent($idempotency_key, $create_bank_payment_intent_dto, string $contentType = self::contentTypes['paymentIntentControllerCreateBankPaymentIntent'][0])
    {
        $this->paymentIntentControllerCreateBankPaymentIntentWithHttpInfo($idempotency_key, $create_bank_payment_intent_dto, $contentType);
    }

    /**
     * Operation paymentIntentControllerCreateBankPaymentIntentWithHttpInfo
     *
     * Create a bank payment intent
     *
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     * @param  \Devdraft\Model\CreateBankPaymentIntentDto $create_bank_payment_intent_dto Bank payment intent creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentIntentControllerCreateBankPaymentIntent'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function paymentIntentControllerCreateBankPaymentIntentWithHttpInfo($idempotency_key, $create_bank_payment_intent_dto, string $contentType = self::contentTypes['paymentIntentControllerCreateBankPaymentIntent'][0])
    {
        $request = $this->paymentIntentControllerCreateBankPaymentIntentRequest($idempotency_key, $create_bank_payment_intent_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation paymentIntentControllerCreateBankPaymentIntentAsync
     *
     * Create a bank payment intent
     *
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     * @param  \Devdraft\Model\CreateBankPaymentIntentDto $create_bank_payment_intent_dto Bank payment intent creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentIntentControllerCreateBankPaymentIntent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentIntentControllerCreateBankPaymentIntentAsync($idempotency_key, $create_bank_payment_intent_dto, string $contentType = self::contentTypes['paymentIntentControllerCreateBankPaymentIntent'][0])
    {
        return $this->paymentIntentControllerCreateBankPaymentIntentAsyncWithHttpInfo($idempotency_key, $create_bank_payment_intent_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation paymentIntentControllerCreateBankPaymentIntentAsyncWithHttpInfo
     *
     * Create a bank payment intent
     *
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     * @param  \Devdraft\Model\CreateBankPaymentIntentDto $create_bank_payment_intent_dto Bank payment intent creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentIntentControllerCreateBankPaymentIntent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentIntentControllerCreateBankPaymentIntentAsyncWithHttpInfo($idempotency_key, $create_bank_payment_intent_dto, string $contentType = self::contentTypes['paymentIntentControllerCreateBankPaymentIntent'][0])
    {
        $returnType = '';
        $request = $this->paymentIntentControllerCreateBankPaymentIntentRequest($idempotency_key, $create_bank_payment_intent_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'paymentIntentControllerCreateBankPaymentIntent'
     *
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     * @param  \Devdraft\Model\CreateBankPaymentIntentDto $create_bank_payment_intent_dto Bank payment intent creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentIntentControllerCreateBankPaymentIntent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function paymentIntentControllerCreateBankPaymentIntentRequest($idempotency_key, $create_bank_payment_intent_dto, string $contentType = self::contentTypes['paymentIntentControllerCreateBankPaymentIntent'][0])
    {

        // verify the required parameter 'idempotency_key' is set
        if ($idempotency_key === null || (is_array($idempotency_key) && count($idempotency_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $idempotency_key when calling paymentIntentControllerCreateBankPaymentIntent'
            );
        }

        // verify the required parameter 'create_bank_payment_intent_dto' is set
        if ($create_bank_payment_intent_dto === null || (is_array($create_bank_payment_intent_dto) && count($create_bank_payment_intent_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_bank_payment_intent_dto when calling paymentIntentControllerCreateBankPaymentIntent'
            );
        }


        $resourcePath = '/api/v0/payment-intents/bank';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotency_key !== null) {
            $headerParams['idempotency-key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_bank_payment_intent_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_bank_payment_intent_dto));
            } else {
                $httpBody = $create_bank_payment_intent_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation paymentIntentControllerCreateStablePaymentIntent
     *
     * Create a stable payment intent
     *
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     * @param  \Devdraft\Model\CreateStablePaymentIntentDto $create_stable_payment_intent_dto Stable payment intent creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentIntentControllerCreateStablePaymentIntent'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function paymentIntentControllerCreateStablePaymentIntent($idempotency_key, $create_stable_payment_intent_dto, string $contentType = self::contentTypes['paymentIntentControllerCreateStablePaymentIntent'][0])
    {
        $this->paymentIntentControllerCreateStablePaymentIntentWithHttpInfo($idempotency_key, $create_stable_payment_intent_dto, $contentType);
    }

    /**
     * Operation paymentIntentControllerCreateStablePaymentIntentWithHttpInfo
     *
     * Create a stable payment intent
     *
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     * @param  \Devdraft\Model\CreateStablePaymentIntentDto $create_stable_payment_intent_dto Stable payment intent creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentIntentControllerCreateStablePaymentIntent'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function paymentIntentControllerCreateStablePaymentIntentWithHttpInfo($idempotency_key, $create_stable_payment_intent_dto, string $contentType = self::contentTypes['paymentIntentControllerCreateStablePaymentIntent'][0])
    {
        $request = $this->paymentIntentControllerCreateStablePaymentIntentRequest($idempotency_key, $create_stable_payment_intent_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation paymentIntentControllerCreateStablePaymentIntentAsync
     *
     * Create a stable payment intent
     *
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     * @param  \Devdraft\Model\CreateStablePaymentIntentDto $create_stable_payment_intent_dto Stable payment intent creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentIntentControllerCreateStablePaymentIntent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentIntentControllerCreateStablePaymentIntentAsync($idempotency_key, $create_stable_payment_intent_dto, string $contentType = self::contentTypes['paymentIntentControllerCreateStablePaymentIntent'][0])
    {
        return $this->paymentIntentControllerCreateStablePaymentIntentAsyncWithHttpInfo($idempotency_key, $create_stable_payment_intent_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation paymentIntentControllerCreateStablePaymentIntentAsyncWithHttpInfo
     *
     * Create a stable payment intent
     *
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     * @param  \Devdraft\Model\CreateStablePaymentIntentDto $create_stable_payment_intent_dto Stable payment intent creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentIntentControllerCreateStablePaymentIntent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function paymentIntentControllerCreateStablePaymentIntentAsyncWithHttpInfo($idempotency_key, $create_stable_payment_intent_dto, string $contentType = self::contentTypes['paymentIntentControllerCreateStablePaymentIntent'][0])
    {
        $returnType = '';
        $request = $this->paymentIntentControllerCreateStablePaymentIntentRequest($idempotency_key, $create_stable_payment_intent_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'paymentIntentControllerCreateStablePaymentIntent'
     *
     * @param  string $idempotency_key Unique UUID v4 for idempotent requests. Prevents duplicate payments. (required)
     * @param  \Devdraft\Model\CreateStablePaymentIntentDto $create_stable_payment_intent_dto Stable payment intent creation data (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['paymentIntentControllerCreateStablePaymentIntent'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function paymentIntentControllerCreateStablePaymentIntentRequest($idempotency_key, $create_stable_payment_intent_dto, string $contentType = self::contentTypes['paymentIntentControllerCreateStablePaymentIntent'][0])
    {

        // verify the required parameter 'idempotency_key' is set
        if ($idempotency_key === null || (is_array($idempotency_key) && count($idempotency_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $idempotency_key when calling paymentIntentControllerCreateStablePaymentIntent'
            );
        }

        // verify the required parameter 'create_stable_payment_intent_dto' is set
        if ($create_stable_payment_intent_dto === null || (is_array($create_stable_payment_intent_dto) && count($create_stable_payment_intent_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_stable_payment_intent_dto when calling paymentIntentControllerCreateStablePaymentIntent'
            );
        }


        $resourcePath = '/api/v0/payment-intents/stablecoin';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotency_key !== null) {
            $headerParams['idempotency-key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_stable_payment_intent_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_stable_payment_intent_dto));
            } else {
                $httpBody = $create_stable_payment_intent_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
