<?php
/**
 * TransfersApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Devdraft\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Devdraft\ApiException;
use Devdraft\Configuration;
use Devdraft\FormDataProcessor;
use Devdraft\HeaderSelector;
use Devdraft\ObjectSerializer;

/**
 * TransfersApi Class Doc Comment
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransfersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'transferControllerCreateDirectBankTransfer' => [
            'application/json',
        ],
        'transferControllerCreateDirectWalletTransfer' => [
            'application/json',
        ],
        'transferControllerCreateExternalBankTransfer' => [
            'application/json',
        ],
        'transferControllerCreateExternalStablecoinTransfer' => [
            'application/json',
        ],
        'transferControllerCreateStablecoinConversion' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation transferControllerCreateDirectBankTransfer
     *
     * Create a direct bank transfer
     *
     * @param  \Devdraft\Model\CreateDirectBankTransferDto $create_direct_bank_transfer_dto create_direct_bank_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateDirectBankTransfer'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function transferControllerCreateDirectBankTransfer($create_direct_bank_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateDirectBankTransfer'][0])
    {
        $this->transferControllerCreateDirectBankTransferWithHttpInfo($create_direct_bank_transfer_dto, $contentType);
    }

    /**
     * Operation transferControllerCreateDirectBankTransferWithHttpInfo
     *
     * Create a direct bank transfer
     *
     * @param  \Devdraft\Model\CreateDirectBankTransferDto $create_direct_bank_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateDirectBankTransfer'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferControllerCreateDirectBankTransferWithHttpInfo($create_direct_bank_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateDirectBankTransfer'][0])
    {
        $request = $this->transferControllerCreateDirectBankTransferRequest($create_direct_bank_transfer_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferControllerCreateDirectBankTransferAsync
     *
     * Create a direct bank transfer
     *
     * @param  \Devdraft\Model\CreateDirectBankTransferDto $create_direct_bank_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateDirectBankTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferControllerCreateDirectBankTransferAsync($create_direct_bank_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateDirectBankTransfer'][0])
    {
        return $this->transferControllerCreateDirectBankTransferAsyncWithHttpInfo($create_direct_bank_transfer_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferControllerCreateDirectBankTransferAsyncWithHttpInfo
     *
     * Create a direct bank transfer
     *
     * @param  \Devdraft\Model\CreateDirectBankTransferDto $create_direct_bank_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateDirectBankTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferControllerCreateDirectBankTransferAsyncWithHttpInfo($create_direct_bank_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateDirectBankTransfer'][0])
    {
        $returnType = '';
        $request = $this->transferControllerCreateDirectBankTransferRequest($create_direct_bank_transfer_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferControllerCreateDirectBankTransfer'
     *
     * @param  \Devdraft\Model\CreateDirectBankTransferDto $create_direct_bank_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateDirectBankTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferControllerCreateDirectBankTransferRequest($create_direct_bank_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateDirectBankTransfer'][0])
    {

        // verify the required parameter 'create_direct_bank_transfer_dto' is set
        if ($create_direct_bank_transfer_dto === null || (is_array($create_direct_bank_transfer_dto) && count($create_direct_bank_transfer_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_direct_bank_transfer_dto when calling transferControllerCreateDirectBankTransfer'
            );
        }


        $resourcePath = '/api/v0/transfers/direct-bank';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_direct_bank_transfer_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_direct_bank_transfer_dto));
            } else {
                $httpBody = $create_direct_bank_transfer_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transferControllerCreateDirectWalletTransfer
     *
     * Create a direct wallet transfer
     *
     * @param  \Devdraft\Model\CreateDirectWalletTransferDto $create_direct_wallet_transfer_dto create_direct_wallet_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateDirectWalletTransfer'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function transferControllerCreateDirectWalletTransfer($create_direct_wallet_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateDirectWalletTransfer'][0])
    {
        $this->transferControllerCreateDirectWalletTransferWithHttpInfo($create_direct_wallet_transfer_dto, $contentType);
    }

    /**
     * Operation transferControllerCreateDirectWalletTransferWithHttpInfo
     *
     * Create a direct wallet transfer
     *
     * @param  \Devdraft\Model\CreateDirectWalletTransferDto $create_direct_wallet_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateDirectWalletTransfer'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferControllerCreateDirectWalletTransferWithHttpInfo($create_direct_wallet_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateDirectWalletTransfer'][0])
    {
        $request = $this->transferControllerCreateDirectWalletTransferRequest($create_direct_wallet_transfer_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferControllerCreateDirectWalletTransferAsync
     *
     * Create a direct wallet transfer
     *
     * @param  \Devdraft\Model\CreateDirectWalletTransferDto $create_direct_wallet_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateDirectWalletTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferControllerCreateDirectWalletTransferAsync($create_direct_wallet_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateDirectWalletTransfer'][0])
    {
        return $this->transferControllerCreateDirectWalletTransferAsyncWithHttpInfo($create_direct_wallet_transfer_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferControllerCreateDirectWalletTransferAsyncWithHttpInfo
     *
     * Create a direct wallet transfer
     *
     * @param  \Devdraft\Model\CreateDirectWalletTransferDto $create_direct_wallet_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateDirectWalletTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferControllerCreateDirectWalletTransferAsyncWithHttpInfo($create_direct_wallet_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateDirectWalletTransfer'][0])
    {
        $returnType = '';
        $request = $this->transferControllerCreateDirectWalletTransferRequest($create_direct_wallet_transfer_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferControllerCreateDirectWalletTransfer'
     *
     * @param  \Devdraft\Model\CreateDirectWalletTransferDto $create_direct_wallet_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateDirectWalletTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferControllerCreateDirectWalletTransferRequest($create_direct_wallet_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateDirectWalletTransfer'][0])
    {

        // verify the required parameter 'create_direct_wallet_transfer_dto' is set
        if ($create_direct_wallet_transfer_dto === null || (is_array($create_direct_wallet_transfer_dto) && count($create_direct_wallet_transfer_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_direct_wallet_transfer_dto when calling transferControllerCreateDirectWalletTransfer'
            );
        }


        $resourcePath = '/api/v0/transfers/direct-wallet';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_direct_wallet_transfer_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_direct_wallet_transfer_dto));
            } else {
                $httpBody = $create_direct_wallet_transfer_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transferControllerCreateExternalBankTransfer
     *
     * Create an external bank transfer
     *
     * @param  \Devdraft\Model\CreateExternalBankTransferDto $create_external_bank_transfer_dto create_external_bank_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateExternalBankTransfer'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function transferControllerCreateExternalBankTransfer($create_external_bank_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateExternalBankTransfer'][0])
    {
        $this->transferControllerCreateExternalBankTransferWithHttpInfo($create_external_bank_transfer_dto, $contentType);
    }

    /**
     * Operation transferControllerCreateExternalBankTransferWithHttpInfo
     *
     * Create an external bank transfer
     *
     * @param  \Devdraft\Model\CreateExternalBankTransferDto $create_external_bank_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateExternalBankTransfer'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferControllerCreateExternalBankTransferWithHttpInfo($create_external_bank_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateExternalBankTransfer'][0])
    {
        $request = $this->transferControllerCreateExternalBankTransferRequest($create_external_bank_transfer_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferControllerCreateExternalBankTransferAsync
     *
     * Create an external bank transfer
     *
     * @param  \Devdraft\Model\CreateExternalBankTransferDto $create_external_bank_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateExternalBankTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferControllerCreateExternalBankTransferAsync($create_external_bank_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateExternalBankTransfer'][0])
    {
        return $this->transferControllerCreateExternalBankTransferAsyncWithHttpInfo($create_external_bank_transfer_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferControllerCreateExternalBankTransferAsyncWithHttpInfo
     *
     * Create an external bank transfer
     *
     * @param  \Devdraft\Model\CreateExternalBankTransferDto $create_external_bank_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateExternalBankTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferControllerCreateExternalBankTransferAsyncWithHttpInfo($create_external_bank_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateExternalBankTransfer'][0])
    {
        $returnType = '';
        $request = $this->transferControllerCreateExternalBankTransferRequest($create_external_bank_transfer_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferControllerCreateExternalBankTransfer'
     *
     * @param  \Devdraft\Model\CreateExternalBankTransferDto $create_external_bank_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateExternalBankTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferControllerCreateExternalBankTransferRequest($create_external_bank_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateExternalBankTransfer'][0])
    {

        // verify the required parameter 'create_external_bank_transfer_dto' is set
        if ($create_external_bank_transfer_dto === null || (is_array($create_external_bank_transfer_dto) && count($create_external_bank_transfer_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_external_bank_transfer_dto when calling transferControllerCreateExternalBankTransfer'
            );
        }


        $resourcePath = '/api/v0/transfers/external-bank-transfer';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_external_bank_transfer_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_external_bank_transfer_dto));
            } else {
                $httpBody = $create_external_bank_transfer_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transferControllerCreateExternalStablecoinTransfer
     *
     * Create an external stablecoin transfer
     *
     * @param  \Devdraft\Model\CreateExternalStablecoinTransferDto $create_external_stablecoin_transfer_dto create_external_stablecoin_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateExternalStablecoinTransfer'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function transferControllerCreateExternalStablecoinTransfer($create_external_stablecoin_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateExternalStablecoinTransfer'][0])
    {
        $this->transferControllerCreateExternalStablecoinTransferWithHttpInfo($create_external_stablecoin_transfer_dto, $contentType);
    }

    /**
     * Operation transferControllerCreateExternalStablecoinTransferWithHttpInfo
     *
     * Create an external stablecoin transfer
     *
     * @param  \Devdraft\Model\CreateExternalStablecoinTransferDto $create_external_stablecoin_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateExternalStablecoinTransfer'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferControllerCreateExternalStablecoinTransferWithHttpInfo($create_external_stablecoin_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateExternalStablecoinTransfer'][0])
    {
        $request = $this->transferControllerCreateExternalStablecoinTransferRequest($create_external_stablecoin_transfer_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferControllerCreateExternalStablecoinTransferAsync
     *
     * Create an external stablecoin transfer
     *
     * @param  \Devdraft\Model\CreateExternalStablecoinTransferDto $create_external_stablecoin_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateExternalStablecoinTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferControllerCreateExternalStablecoinTransferAsync($create_external_stablecoin_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateExternalStablecoinTransfer'][0])
    {
        return $this->transferControllerCreateExternalStablecoinTransferAsyncWithHttpInfo($create_external_stablecoin_transfer_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferControllerCreateExternalStablecoinTransferAsyncWithHttpInfo
     *
     * Create an external stablecoin transfer
     *
     * @param  \Devdraft\Model\CreateExternalStablecoinTransferDto $create_external_stablecoin_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateExternalStablecoinTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferControllerCreateExternalStablecoinTransferAsyncWithHttpInfo($create_external_stablecoin_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateExternalStablecoinTransfer'][0])
    {
        $returnType = '';
        $request = $this->transferControllerCreateExternalStablecoinTransferRequest($create_external_stablecoin_transfer_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferControllerCreateExternalStablecoinTransfer'
     *
     * @param  \Devdraft\Model\CreateExternalStablecoinTransferDto $create_external_stablecoin_transfer_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateExternalStablecoinTransfer'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferControllerCreateExternalStablecoinTransferRequest($create_external_stablecoin_transfer_dto, string $contentType = self::contentTypes['transferControllerCreateExternalStablecoinTransfer'][0])
    {

        // verify the required parameter 'create_external_stablecoin_transfer_dto' is set
        if ($create_external_stablecoin_transfer_dto === null || (is_array($create_external_stablecoin_transfer_dto) && count($create_external_stablecoin_transfer_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_external_stablecoin_transfer_dto when calling transferControllerCreateExternalStablecoinTransfer'
            );
        }


        $resourcePath = '/api/v0/transfers/external-stablecoin-transfer';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_external_stablecoin_transfer_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_external_stablecoin_transfer_dto));
            } else {
                $httpBody = $create_external_stablecoin_transfer_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transferControllerCreateStablecoinConversion
     *
     * Create a stablecoin conversion
     *
     * @param  \Devdraft\Model\CreateStablecoinConversionDto $create_stablecoin_conversion_dto create_stablecoin_conversion_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateStablecoinConversion'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function transferControllerCreateStablecoinConversion($create_stablecoin_conversion_dto, string $contentType = self::contentTypes['transferControllerCreateStablecoinConversion'][0])
    {
        $this->transferControllerCreateStablecoinConversionWithHttpInfo($create_stablecoin_conversion_dto, $contentType);
    }

    /**
     * Operation transferControllerCreateStablecoinConversionWithHttpInfo
     *
     * Create a stablecoin conversion
     *
     * @param  \Devdraft\Model\CreateStablecoinConversionDto $create_stablecoin_conversion_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateStablecoinConversion'] to see the possible values for this operation
     *
     * @throws \Devdraft\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function transferControllerCreateStablecoinConversionWithHttpInfo($create_stablecoin_conversion_dto, string $contentType = self::contentTypes['transferControllerCreateStablecoinConversion'][0])
    {
        $request = $this->transferControllerCreateStablecoinConversionRequest($create_stablecoin_conversion_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation transferControllerCreateStablecoinConversionAsync
     *
     * Create a stablecoin conversion
     *
     * @param  \Devdraft\Model\CreateStablecoinConversionDto $create_stablecoin_conversion_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateStablecoinConversion'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferControllerCreateStablecoinConversionAsync($create_stablecoin_conversion_dto, string $contentType = self::contentTypes['transferControllerCreateStablecoinConversion'][0])
    {
        return $this->transferControllerCreateStablecoinConversionAsyncWithHttpInfo($create_stablecoin_conversion_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transferControllerCreateStablecoinConversionAsyncWithHttpInfo
     *
     * Create a stablecoin conversion
     *
     * @param  \Devdraft\Model\CreateStablecoinConversionDto $create_stablecoin_conversion_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateStablecoinConversion'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transferControllerCreateStablecoinConversionAsyncWithHttpInfo($create_stablecoin_conversion_dto, string $contentType = self::contentTypes['transferControllerCreateStablecoinConversion'][0])
    {
        $returnType = '';
        $request = $this->transferControllerCreateStablecoinConversionRequest($create_stablecoin_conversion_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transferControllerCreateStablecoinConversion'
     *
     * @param  \Devdraft\Model\CreateStablecoinConversionDto $create_stablecoin_conversion_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['transferControllerCreateStablecoinConversion'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transferControllerCreateStablecoinConversionRequest($create_stablecoin_conversion_dto, string $contentType = self::contentTypes['transferControllerCreateStablecoinConversion'][0])
    {

        // verify the required parameter 'create_stablecoin_conversion_dto' is set
        if ($create_stablecoin_conversion_dto === null || (is_array($create_stablecoin_conversion_dto) && count($create_stablecoin_conversion_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_stablecoin_conversion_dto when calling transferControllerCreateStablecoinConversion'
            );
        }


        $resourcePath = '/api/v0/transfers/stablecoin-conversion';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_stablecoin_conversion_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_stablecoin_conversion_dto));
            } else {
                $httpBody = $create_stablecoin_conversion_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-secret');
        if ($apiKey !== null) {
            $headers['x-client-secret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-client-key');
        if ($apiKey !== null) {
            $headers['x-client-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
