<?php
/**
 * BridgePaymentRail
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Devdraft\Model;
use \Devdraft\ObjectSerializer;

/**
 * BridgePaymentRail Class Doc Comment
 *
 * @category Class
 * @description The blockchain network where the source currency resides. Determines gas fees and transaction speed.
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BridgePaymentRail
{
    /**
     * Possible values of this enum
     */
    public const ETHEREUM = 'ethereum';

    public const SOLANA = 'solana';

    public const POLYGON = 'polygon';

    public const AVALANCHE_C_CHAIN = 'avalanche_c_chain';

    public const BASE = 'base';

    public const ARBITRUM = 'arbitrum';

    public const OPTIMISM = 'optimism';

    public const STELLAR = 'stellar';

    public const TRON = 'tron';

    public const BRIDGE_WALLET = 'bridge_wallet';

    public const WIRE = 'wire';

    public const ACH = 'ach';

    public const ACH_PUSH = 'ach_push';

    public const ACH_SAME_DAY = 'ach_same_day';

    public const SEPA = 'sepa';

    public const SWIFT = 'swift';

    public const SPEI = 'spei';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ETHEREUM,
            self::SOLANA,
            self::POLYGON,
            self::AVALANCHE_C_CHAIN,
            self::BASE,
            self::ARBITRUM,
            self::OPTIMISM,
            self::STELLAR,
            self::TRON,
            self::BRIDGE_WALLET,
            self::WIRE,
            self::ACH,
            self::ACH_PUSH,
            self::ACH_SAME_DAY,
            self::SEPA,
            self::SWIFT,
            self::SPEI
        ];
    }
}


