<?php
/**
 * CreateExternalBankTransferDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Devdraft\Model;

use \ArrayAccess;
use \Devdraft\ObjectSerializer;

/**
 * CreateExternalBankTransferDto Class Doc Comment
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateExternalBankTransferDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateExternalBankTransferDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'source_wallet_id' => 'string',
        'source_currency' => 'string',
        'destination_currency' => 'string',
        'destination_payment_rail' => '\Devdraft\Model\BridgeFiatPaymentRail',
        'external_account_id' => 'string',
        'amount' => 'float',
        'wire_message' => 'string',
        'sepa_reference' => 'string',
        'swift_reference' => 'string',
        'spei_reference' => 'string',
        'swift_charges' => 'string',
        'ach_reference' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'source_wallet_id' => null,
        'source_currency' => null,
        'destination_currency' => null,
        'destination_payment_rail' => null,
        'external_account_id' => null,
        'amount' => null,
        'wire_message' => null,
        'sepa_reference' => null,
        'swift_reference' => null,
        'spei_reference' => null,
        'swift_charges' => null,
        'ach_reference' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'source_wallet_id' => false,
        'source_currency' => false,
        'destination_currency' => false,
        'destination_payment_rail' => false,
        'external_account_id' => false,
        'amount' => false,
        'wire_message' => false,
        'sepa_reference' => false,
        'swift_reference' => false,
        'spei_reference' => false,
        'swift_charges' => false,
        'ach_reference' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'source_wallet_id' => 'sourceWalletId',
        'source_currency' => 'sourceCurrency',
        'destination_currency' => 'destinationCurrency',
        'destination_payment_rail' => 'destinationPaymentRail',
        'external_account_id' => 'external_account_id',
        'amount' => 'amount',
        'wire_message' => 'wire_message',
        'sepa_reference' => 'sepa_reference',
        'swift_reference' => 'swift_reference',
        'spei_reference' => 'spei_reference',
        'swift_charges' => 'swift_charges',
        'ach_reference' => 'ach_reference'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'source_wallet_id' => 'setSourceWalletId',
        'source_currency' => 'setSourceCurrency',
        'destination_currency' => 'setDestinationCurrency',
        'destination_payment_rail' => 'setDestinationPaymentRail',
        'external_account_id' => 'setExternalAccountId',
        'amount' => 'setAmount',
        'wire_message' => 'setWireMessage',
        'sepa_reference' => 'setSepaReference',
        'swift_reference' => 'setSwiftReference',
        'spei_reference' => 'setSpeiReference',
        'swift_charges' => 'setSwiftCharges',
        'ach_reference' => 'setAchReference'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'source_wallet_id' => 'getSourceWalletId',
        'source_currency' => 'getSourceCurrency',
        'destination_currency' => 'getDestinationCurrency',
        'destination_payment_rail' => 'getDestinationPaymentRail',
        'external_account_id' => 'getExternalAccountId',
        'amount' => 'getAmount',
        'wire_message' => 'getWireMessage',
        'sepa_reference' => 'getSepaReference',
        'swift_reference' => 'getSwiftReference',
        'spei_reference' => 'getSpeiReference',
        'swift_charges' => 'getSwiftCharges',
        'ach_reference' => 'getAchReference'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('source_wallet_id', $data ?? [], null);
        $this->setIfExists('source_currency', $data ?? [], null);
        $this->setIfExists('destination_currency', $data ?? [], null);
        $this->setIfExists('destination_payment_rail', $data ?? [], null);
        $this->setIfExists('external_account_id', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('wire_message', $data ?? [], null);
        $this->setIfExists('sepa_reference', $data ?? [], null);
        $this->setIfExists('swift_reference', $data ?? [], null);
        $this->setIfExists('spei_reference', $data ?? [], null);
        $this->setIfExists('swift_charges', $data ?? [], null);
        $this->setIfExists('ach_reference', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['source_wallet_id'] === null) {
            $invalidProperties[] = "'source_wallet_id' can't be null";
        }
        if ($this->container['source_currency'] === null) {
            $invalidProperties[] = "'source_currency' can't be null";
        }
        if ($this->container['destination_currency'] === null) {
            $invalidProperties[] = "'destination_currency' can't be null";
        }
        if ($this->container['destination_payment_rail'] === null) {
            $invalidProperties[] = "'destination_payment_rail' can't be null";
        }
        if ($this->container['external_account_id'] === null) {
            $invalidProperties[] = "'external_account_id' can't be null";
        }
        if (!is_null($this->container['wire_message']) && (mb_strlen($this->container['wire_message']) > 256)) {
            $invalidProperties[] = "invalid value for 'wire_message', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['wire_message']) && (mb_strlen($this->container['wire_message']) < 1)) {
            $invalidProperties[] = "invalid value for 'wire_message', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['sepa_reference']) && (mb_strlen($this->container['sepa_reference']) > 140)) {
            $invalidProperties[] = "invalid value for 'sepa_reference', the character length must be smaller than or equal to 140.";
        }

        if (!is_null($this->container['sepa_reference']) && (mb_strlen($this->container['sepa_reference']) < 6)) {
            $invalidProperties[] = "invalid value for 'sepa_reference', the character length must be bigger than or equal to 6.";
        }

        if (!is_null($this->container['swift_reference']) && (mb_strlen($this->container['swift_reference']) > 190)) {
            $invalidProperties[] = "invalid value for 'swift_reference', the character length must be smaller than or equal to 190.";
        }

        if (!is_null($this->container['swift_reference']) && (mb_strlen($this->container['swift_reference']) < 1)) {
            $invalidProperties[] = "invalid value for 'swift_reference', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['spei_reference']) && (mb_strlen($this->container['spei_reference']) > 40)) {
            $invalidProperties[] = "invalid value for 'spei_reference', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['spei_reference']) && (mb_strlen($this->container['spei_reference']) < 1)) {
            $invalidProperties[] = "invalid value for 'spei_reference', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['ach_reference']) && (mb_strlen($this->container['ach_reference']) > 10)) {
            $invalidProperties[] = "invalid value for 'ach_reference', the character length must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['ach_reference']) && (mb_strlen($this->container['ach_reference']) < 1)) {
            $invalidProperties[] = "invalid value for 'ach_reference', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets source_wallet_id
     *
     * @return string
     */
    public function getSourceWalletId()
    {
        return $this->container['source_wallet_id'];
    }

    /**
     * Sets source_wallet_id
     *
     * @param string $source_wallet_id The ID of the source bridge wallet
     *
     * @return self
     */
    public function setSourceWalletId($source_wallet_id)
    {
        if (is_null($source_wallet_id)) {
            throw new \InvalidArgumentException('non-nullable source_wallet_id cannot be null');
        }
        $this->container['source_wallet_id'] = $source_wallet_id;

        return $this;
    }

    /**
     * Gets source_currency
     *
     * @return string
     */
    public function getSourceCurrency()
    {
        return $this->container['source_currency'];
    }

    /**
     * Sets source_currency
     *
     * @param string $source_currency The source currency
     *
     * @return self
     */
    public function setSourceCurrency($source_currency)
    {
        if (is_null($source_currency)) {
            throw new \InvalidArgumentException('non-nullable source_currency cannot be null');
        }
        $this->container['source_currency'] = $source_currency;

        return $this;
    }

    /**
     * Gets destination_currency
     *
     * @return string
     */
    public function getDestinationCurrency()
    {
        return $this->container['destination_currency'];
    }

    /**
     * Sets destination_currency
     *
     * @param string $destination_currency The destination currency
     *
     * @return self
     */
    public function setDestinationCurrency($destination_currency)
    {
        if (is_null($destination_currency)) {
            throw new \InvalidArgumentException('non-nullable destination_currency cannot be null');
        }
        $this->container['destination_currency'] = $destination_currency;

        return $this;
    }

    /**
     * Gets destination_payment_rail
     *
     * @return \Devdraft\Model\BridgeFiatPaymentRail
     */
    public function getDestinationPaymentRail()
    {
        return $this->container['destination_payment_rail'];
    }

    /**
     * Sets destination_payment_rail
     *
     * @param \Devdraft\Model\BridgeFiatPaymentRail $destination_payment_rail The destination payment rail (fiat payment method)
     *
     * @return self
     */
    public function setDestinationPaymentRail($destination_payment_rail)
    {
        if (is_null($destination_payment_rail)) {
            throw new \InvalidArgumentException('non-nullable destination_payment_rail cannot be null');
        }
        $this->container['destination_payment_rail'] = $destination_payment_rail;

        return $this;
    }

    /**
     * Gets external_account_id
     *
     * @return string
     */
    public function getExternalAccountId()
    {
        return $this->container['external_account_id'];
    }

    /**
     * Sets external_account_id
     *
     * @param string $external_account_id The external account ID for the bank transfer
     *
     * @return self
     */
    public function setExternalAccountId($external_account_id)
    {
        if (is_null($external_account_id)) {
            throw new \InvalidArgumentException('non-nullable external_account_id cannot be null');
        }
        $this->container['external_account_id'] = $external_account_id;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float|null $amount The amount to transfer
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets wire_message
     *
     * @return string|null
     */
    public function getWireMessage()
    {
        return $this->container['wire_message'];
    }

    /**
     * Sets wire_message
     *
     * @param string|null $wire_message Wire transfer message (1-256 characters, only for wire transfers)
     *
     * @return self
     */
    public function setWireMessage($wire_message)
    {
        if (is_null($wire_message)) {
            throw new \InvalidArgumentException('non-nullable wire_message cannot be null');
        }
        if ((mb_strlen($wire_message) > 256)) {
            throw new \InvalidArgumentException('invalid length for $wire_message when calling CreateExternalBankTransferDto., must be smaller than or equal to 256.');
        }
        if ((mb_strlen($wire_message) < 1)) {
            throw new \InvalidArgumentException('invalid length for $wire_message when calling CreateExternalBankTransferDto., must be bigger than or equal to 1.');
        }

        $this->container['wire_message'] = $wire_message;

        return $this;
    }

    /**
     * Gets sepa_reference
     *
     * @return string|null
     */
    public function getSepaReference()
    {
        return $this->container['sepa_reference'];
    }

    /**
     * Sets sepa_reference
     *
     * @param string|null $sepa_reference SEPA reference message (6-140 characters, only for SEPA transfers)
     *
     * @return self
     */
    public function setSepaReference($sepa_reference)
    {
        if (is_null($sepa_reference)) {
            throw new \InvalidArgumentException('non-nullable sepa_reference cannot be null');
        }
        if ((mb_strlen($sepa_reference) > 140)) {
            throw new \InvalidArgumentException('invalid length for $sepa_reference when calling CreateExternalBankTransferDto., must be smaller than or equal to 140.');
        }
        if ((mb_strlen($sepa_reference) < 6)) {
            throw new \InvalidArgumentException('invalid length for $sepa_reference when calling CreateExternalBankTransferDto., must be bigger than or equal to 6.');
        }

        $this->container['sepa_reference'] = $sepa_reference;

        return $this;
    }

    /**
     * Gets swift_reference
     *
     * @return string|null
     */
    public function getSwiftReference()
    {
        return $this->container['swift_reference'];
    }

    /**
     * Sets swift_reference
     *
     * @param string|null $swift_reference SWIFT reference message (1-190 characters, only for SWIFT transfers)
     *
     * @return self
     */
    public function setSwiftReference($swift_reference)
    {
        if (is_null($swift_reference)) {
            throw new \InvalidArgumentException('non-nullable swift_reference cannot be null');
        }
        if ((mb_strlen($swift_reference) > 190)) {
            throw new \InvalidArgumentException('invalid length for $swift_reference when calling CreateExternalBankTransferDto., must be smaller than or equal to 190.');
        }
        if ((mb_strlen($swift_reference) < 1)) {
            throw new \InvalidArgumentException('invalid length for $swift_reference when calling CreateExternalBankTransferDto., must be bigger than or equal to 1.');
        }

        $this->container['swift_reference'] = $swift_reference;

        return $this;
    }

    /**
     * Gets spei_reference
     *
     * @return string|null
     */
    public function getSpeiReference()
    {
        return $this->container['spei_reference'];
    }

    /**
     * Sets spei_reference
     *
     * @param string|null $spei_reference SPEI reference message (1-40 characters, only for SPEI transfers)
     *
     * @return self
     */
    public function setSpeiReference($spei_reference)
    {
        if (is_null($spei_reference)) {
            throw new \InvalidArgumentException('non-nullable spei_reference cannot be null');
        }
        if ((mb_strlen($spei_reference) > 40)) {
            throw new \InvalidArgumentException('invalid length for $spei_reference when calling CreateExternalBankTransferDto., must be smaller than or equal to 40.');
        }
        if ((mb_strlen($spei_reference) < 1)) {
            throw new \InvalidArgumentException('invalid length for $spei_reference when calling CreateExternalBankTransferDto., must be bigger than or equal to 1.');
        }

        $this->container['spei_reference'] = $spei_reference;

        return $this;
    }

    /**
     * Gets swift_charges
     *
     * @return string|null
     */
    public function getSwiftCharges()
    {
        return $this->container['swift_charges'];
    }

    /**
     * Sets swift_charges
     *
     * @param string|null $swift_charges SWIFT charges bearer (only for SWIFT transfers)
     *
     * @return self
     */
    public function setSwiftCharges($swift_charges)
    {
        if (is_null($swift_charges)) {
            throw new \InvalidArgumentException('non-nullable swift_charges cannot be null');
        }
        $this->container['swift_charges'] = $swift_charges;

        return $this;
    }

    /**
     * Gets ach_reference
     *
     * @return string|null
     */
    public function getAchReference()
    {
        return $this->container['ach_reference'];
    }

    /**
     * Sets ach_reference
     *
     * @param string|null $ach_reference ACH reference message (1-10 characters, only for ACH transfers)
     *
     * @return self
     */
    public function setAchReference($ach_reference)
    {
        if (is_null($ach_reference)) {
            throw new \InvalidArgumentException('non-nullable ach_reference cannot be null');
        }
        if ((mb_strlen($ach_reference) > 10)) {
            throw new \InvalidArgumentException('invalid length for $ach_reference when calling CreateExternalBankTransferDto., must be smaller than or equal to 10.');
        }
        if ((mb_strlen($ach_reference) < 1)) {
            throw new \InvalidArgumentException('invalid length for $ach_reference when calling CreateExternalBankTransferDto., must be bigger than or equal to 1.');
        }

        $this->container['ach_reference'] = $ach_reference;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


