<?php
/**
 * CreatePaymentLinkDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Devdraft\Model;

use \ArrayAccess;
use \Devdraft\ObjectSerializer;

/**
 * CreatePaymentLinkDto Class Doc Comment
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreatePaymentLinkDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreatePaymentLinkDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'title' => 'string',
        'url' => 'string',
        'description' => 'string',
        'cover_image' => 'string',
        'link_type' => 'string',
        'amount' => 'float',
        'payment_for_id' => 'string',
        'customer_id' => 'string',
        'payment_link_products' => '\Devdraft\Model\PaymentLinkProductDto[]',
        'is_for_all_product' => 'bool',
        'allow_quantity_adjustment' => 'bool',
        'collect_tax' => 'bool',
        'tax_id' => 'string',
        'collect_address' => 'bool',
        'limit_payments' => 'bool',
        'max_payments' => 'float',
        'custom_fields' => 'object',
        'allow_mobile_payment' => 'bool',
        'currency' => 'string',
        'expiration_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'title' => null,
        'url' => null,
        'description' => null,
        'cover_image' => null,
        'link_type' => null,
        'amount' => null,
        'payment_for_id' => null,
        'customer_id' => null,
        'payment_link_products' => null,
        'is_for_all_product' => null,
        'allow_quantity_adjustment' => null,
        'collect_tax' => null,
        'tax_id' => null,
        'collect_address' => null,
        'limit_payments' => null,
        'max_payments' => null,
        'custom_fields' => null,
        'allow_mobile_payment' => null,
        'currency' => null,
        'expiration_date' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'title' => false,
        'url' => false,
        'description' => false,
        'cover_image' => false,
        'link_type' => false,
        'amount' => false,
        'payment_for_id' => false,
        'customer_id' => false,
        'payment_link_products' => false,
        'is_for_all_product' => false,
        'allow_quantity_adjustment' => false,
        'collect_tax' => false,
        'tax_id' => false,
        'collect_address' => false,
        'limit_payments' => false,
        'max_payments' => false,
        'custom_fields' => false,
        'allow_mobile_payment' => false,
        'currency' => false,
        'expiration_date' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'title' => 'title',
        'url' => 'url',
        'description' => 'description',
        'cover_image' => 'coverImage',
        'link_type' => 'linkType',
        'amount' => 'amount',
        'payment_for_id' => 'paymentForId',
        'customer_id' => 'customerId',
        'payment_link_products' => 'paymentLinkProducts',
        'is_for_all_product' => 'isForAllProduct',
        'allow_quantity_adjustment' => 'allowQuantityAdjustment',
        'collect_tax' => 'collectTax',
        'tax_id' => 'taxId',
        'collect_address' => 'collectAddress',
        'limit_payments' => 'limitPayments',
        'max_payments' => 'maxPayments',
        'custom_fields' => 'customFields',
        'allow_mobile_payment' => 'allowMobilePayment',
        'currency' => 'currency',
        'expiration_date' => 'expiration_date'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'title' => 'setTitle',
        'url' => 'setUrl',
        'description' => 'setDescription',
        'cover_image' => 'setCoverImage',
        'link_type' => 'setLinkType',
        'amount' => 'setAmount',
        'payment_for_id' => 'setPaymentForId',
        'customer_id' => 'setCustomerId',
        'payment_link_products' => 'setPaymentLinkProducts',
        'is_for_all_product' => 'setIsForAllProduct',
        'allow_quantity_adjustment' => 'setAllowQuantityAdjustment',
        'collect_tax' => 'setCollectTax',
        'tax_id' => 'setTaxId',
        'collect_address' => 'setCollectAddress',
        'limit_payments' => 'setLimitPayments',
        'max_payments' => 'setMaxPayments',
        'custom_fields' => 'setCustomFields',
        'allow_mobile_payment' => 'setAllowMobilePayment',
        'currency' => 'setCurrency',
        'expiration_date' => 'setExpirationDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'title' => 'getTitle',
        'url' => 'getUrl',
        'description' => 'getDescription',
        'cover_image' => 'getCoverImage',
        'link_type' => 'getLinkType',
        'amount' => 'getAmount',
        'payment_for_id' => 'getPaymentForId',
        'customer_id' => 'getCustomerId',
        'payment_link_products' => 'getPaymentLinkProducts',
        'is_for_all_product' => 'getIsForAllProduct',
        'allow_quantity_adjustment' => 'getAllowQuantityAdjustment',
        'collect_tax' => 'getCollectTax',
        'tax_id' => 'getTaxId',
        'collect_address' => 'getCollectAddress',
        'limit_payments' => 'getLimitPayments',
        'max_payments' => 'getMaxPayments',
        'custom_fields' => 'getCustomFields',
        'allow_mobile_payment' => 'getAllowMobilePayment',
        'currency' => 'getCurrency',
        'expiration_date' => 'getExpirationDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const LINK_TYPE_INVOICE = 'INVOICE';
    public const LINK_TYPE_PRODUCT = 'PRODUCT';
    public const LINK_TYPE_COLLECTION = 'COLLECTION';
    public const LINK_TYPE_DONATION = 'DONATION';
    public const CURRENCY_USDC = 'usdc';
    public const CURRENCY_EURC = 'eurc';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLinkTypeAllowableValues()
    {
        return [
            self::LINK_TYPE_INVOICE,
            self::LINK_TYPE_PRODUCT,
            self::LINK_TYPE_COLLECTION,
            self::LINK_TYPE_DONATION,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCurrencyAllowableValues()
    {
        return [
            self::CURRENCY_USDC,
            self::CURRENCY_EURC,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('cover_image', $data ?? [], null);
        $this->setIfExists('link_type', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('payment_for_id', $data ?? [], null);
        $this->setIfExists('customer_id', $data ?? [], null);
        $this->setIfExists('payment_link_products', $data ?? [], null);
        $this->setIfExists('is_for_all_product', $data ?? [], false);
        $this->setIfExists('allow_quantity_adjustment', $data ?? [], true);
        $this->setIfExists('collect_tax', $data ?? [], false);
        $this->setIfExists('tax_id', $data ?? [], null);
        $this->setIfExists('collect_address', $data ?? [], false);
        $this->setIfExists('limit_payments', $data ?? [], false);
        $this->setIfExists('max_payments', $data ?? [], null);
        $this->setIfExists('custom_fields', $data ?? [], null);
        $this->setIfExists('allow_mobile_payment', $data ?? [], false);
        $this->setIfExists('currency', $data ?? [], 'usdc');
        $this->setIfExists('expiration_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ((mb_strlen($this->container['title']) > 100)) {
            $invalidProperties[] = "invalid value for 'title', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['title']) < 3)) {
            $invalidProperties[] = "invalid value for 'title', the character length must be bigger than or equal to 3.";
        }

        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 500)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 500.";
        }

        if ($this->container['link_type'] === null) {
            $invalidProperties[] = "'link_type' can't be null";
        }
        $allowedValues = $this->getLinkTypeAllowableValues();
        if (!is_null($this->container['link_type']) && !in_array($this->container['link_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'link_type', must be one of '%s'",
                $this->container['link_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['amount']) && ($this->container['amount'] < 0.01)) {
            $invalidProperties[] = "invalid value for 'amount', must be bigger than or equal to 0.01.";
        }

        if ($this->container['allow_quantity_adjustment'] === null) {
            $invalidProperties[] = "'allow_quantity_adjustment' can't be null";
        }
        if ($this->container['collect_tax'] === null) {
            $invalidProperties[] = "'collect_tax' can't be null";
        }
        if ($this->container['collect_address'] === null) {
            $invalidProperties[] = "'collect_address' can't be null";
        }
        if (!is_null($this->container['max_payments']) && ($this->container['max_payments'] < 1)) {
            $invalidProperties[] = "invalid value for 'max_payments', must be bigger than or equal to 1.";
        }

        if ($this->container['allow_mobile_payment'] === null) {
            $invalidProperties[] = "'allow_mobile_payment' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalidProperties[] = "'currency' can't be null";
        }
        $allowedValues = $this->getCurrencyAllowableValues();
        if (!is_null($this->container['currency']) && !in_array($this->container['currency'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'currency', must be one of '%s'",
                $this->container['currency'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title Display title for the payment link. This appears on the checkout page and in customer communications.
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        if ((mb_strlen($title) > 100)) {
            throw new \InvalidArgumentException('invalid length for $title when calling CreatePaymentLinkDto., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($title) < 3)) {
            throw new \InvalidArgumentException('invalid length for $title when calling CreatePaymentLinkDto., must be bigger than or equal to 3.');
        }

        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url Unique URL slug for the payment link. Can be a full URL or just the path segment. Must be unique within your account.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Detailed description of what the customer is purchasing. Supports markdown formatting.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 500)) {
            throw new \InvalidArgumentException('invalid length for $description when calling CreatePaymentLinkDto., must be smaller than or equal to 500.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets cover_image
     *
     * @return string|null
     */
    public function getCoverImage()
    {
        return $this->container['cover_image'];
    }

    /**
     * Sets cover_image
     *
     * @param string|null $cover_image Cover image URL
     *
     * @return self
     */
    public function setCoverImage($cover_image)
    {
        if (is_null($cover_image)) {
            throw new \InvalidArgumentException('non-nullable cover_image cannot be null');
        }
        $this->container['cover_image'] = $cover_image;

        return $this;
    }

    /**
     * Gets link_type
     *
     * @return string
     */
    public function getLinkType()
    {
        return $this->container['link_type'];
    }

    /**
     * Sets link_type
     *
     * @param string $link_type Type of the payment link
     *
     * @return self
     */
    public function setLinkType($link_type)
    {
        if (is_null($link_type)) {
            throw new \InvalidArgumentException('non-nullable link_type cannot be null');
        }
        $allowedValues = $this->getLinkTypeAllowableValues();
        if (!in_array($link_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'link_type', must be one of '%s'",
                    $link_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['link_type'] = $link_type;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float|null $amount Amount for the payment link
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }

        if (($amount < 0.01)) {
            throw new \InvalidArgumentException('invalid value for $amount when calling CreatePaymentLinkDto., must be bigger than or equal to 0.01.');
        }

        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets payment_for_id
     *
     * @return string|null
     */
    public function getPaymentForId()
    {
        return $this->container['payment_for_id'];
    }

    /**
     * Sets payment_for_id
     *
     * @param string|null $payment_for_id Payment for ID
     *
     * @return self
     */
    public function setPaymentForId($payment_for_id)
    {
        if (is_null($payment_for_id)) {
            throw new \InvalidArgumentException('non-nullable payment_for_id cannot be null');
        }
        $this->container['payment_for_id'] = $payment_for_id;

        return $this;
    }

    /**
     * Gets customer_id
     *
     * @return string|null
     */
    public function getCustomerId()
    {
        return $this->container['customer_id'];
    }

    /**
     * Sets customer_id
     *
     * @param string|null $customer_id Customer ID
     *
     * @return self
     */
    public function setCustomerId($customer_id)
    {
        if (is_null($customer_id)) {
            throw new \InvalidArgumentException('non-nullable customer_id cannot be null');
        }
        $this->container['customer_id'] = $customer_id;

        return $this;
    }

    /**
     * Gets payment_link_products
     *
     * @return \Devdraft\Model\PaymentLinkProductDto[]|null
     */
    public function getPaymentLinkProducts()
    {
        return $this->container['payment_link_products'];
    }

    /**
     * Sets payment_link_products
     *
     * @param \Devdraft\Model\PaymentLinkProductDto[]|null $payment_link_products Array of products in the payment link
     *
     * @return self
     */
    public function setPaymentLinkProducts($payment_link_products)
    {
        if (is_null($payment_link_products)) {
            throw new \InvalidArgumentException('non-nullable payment_link_products cannot be null');
        }
        $this->container['payment_link_products'] = $payment_link_products;

        return $this;
    }

    /**
     * Gets is_for_all_product
     *
     * @return bool|null
     */
    public function getIsForAllProduct()
    {
        return $this->container['is_for_all_product'];
    }

    /**
     * Sets is_for_all_product
     *
     * @param bool|null $is_for_all_product Whether the payment link is for all products
     *
     * @return self
     */
    public function setIsForAllProduct($is_for_all_product)
    {
        if (is_null($is_for_all_product)) {
            throw new \InvalidArgumentException('non-nullable is_for_all_product cannot be null');
        }
        $this->container['is_for_all_product'] = $is_for_all_product;

        return $this;
    }

    /**
     * Gets allow_quantity_adjustment
     *
     * @return bool
     */
    public function getAllowQuantityAdjustment()
    {
        return $this->container['allow_quantity_adjustment'];
    }

    /**
     * Sets allow_quantity_adjustment
     *
     * @param bool $allow_quantity_adjustment Whether to allow quantity adjustment
     *
     * @return self
     */
    public function setAllowQuantityAdjustment($allow_quantity_adjustment)
    {
        if (is_null($allow_quantity_adjustment)) {
            throw new \InvalidArgumentException('non-nullable allow_quantity_adjustment cannot be null');
        }
        $this->container['allow_quantity_adjustment'] = $allow_quantity_adjustment;

        return $this;
    }

    /**
     * Gets collect_tax
     *
     * @return bool
     */
    public function getCollectTax()
    {
        return $this->container['collect_tax'];
    }

    /**
     * Sets collect_tax
     *
     * @param bool $collect_tax Whether to collect tax
     *
     * @return self
     */
    public function setCollectTax($collect_tax)
    {
        if (is_null($collect_tax)) {
            throw new \InvalidArgumentException('non-nullable collect_tax cannot be null');
        }
        $this->container['collect_tax'] = $collect_tax;

        return $this;
    }

    /**
     * Gets tax_id
     *
     * @return string|null
     */
    public function getTaxId()
    {
        return $this->container['tax_id'];
    }

    /**
     * Sets tax_id
     *
     * @param string|null $tax_id Tax ID
     *
     * @return self
     */
    public function setTaxId($tax_id)
    {
        if (is_null($tax_id)) {
            throw new \InvalidArgumentException('non-nullable tax_id cannot be null');
        }
        $this->container['tax_id'] = $tax_id;

        return $this;
    }

    /**
     * Gets collect_address
     *
     * @return bool
     */
    public function getCollectAddress()
    {
        return $this->container['collect_address'];
    }

    /**
     * Sets collect_address
     *
     * @param bool $collect_address Whether to collect address
     *
     * @return self
     */
    public function setCollectAddress($collect_address)
    {
        if (is_null($collect_address)) {
            throw new \InvalidArgumentException('non-nullable collect_address cannot be null');
        }
        $this->container['collect_address'] = $collect_address;

        return $this;
    }

    /**
     * Gets limit_payments
     *
     * @return bool|null
     */
    public function getLimitPayments()
    {
        return $this->container['limit_payments'];
    }

    /**
     * Sets limit_payments
     *
     * @param bool|null $limit_payments Whether to limit payments
     *
     * @return self
     */
    public function setLimitPayments($limit_payments)
    {
        if (is_null($limit_payments)) {
            throw new \InvalidArgumentException('non-nullable limit_payments cannot be null');
        }
        $this->container['limit_payments'] = $limit_payments;

        return $this;
    }

    /**
     * Gets max_payments
     *
     * @return float|null
     */
    public function getMaxPayments()
    {
        return $this->container['max_payments'];
    }

    /**
     * Sets max_payments
     *
     * @param float|null $max_payments Maximum number of payments
     *
     * @return self
     */
    public function setMaxPayments($max_payments)
    {
        if (is_null($max_payments)) {
            throw new \InvalidArgumentException('non-nullable max_payments cannot be null');
        }

        if (($max_payments < 1)) {
            throw new \InvalidArgumentException('invalid value for $max_payments when calling CreatePaymentLinkDto., must be bigger than or equal to 1.');
        }

        $this->container['max_payments'] = $max_payments;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return object|null
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param object|null $custom_fields Custom fields
     *
     * @return self
     */
    public function setCustomFields($custom_fields)
    {
        if (is_null($custom_fields)) {
            throw new \InvalidArgumentException('non-nullable custom_fields cannot be null');
        }
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }

    /**
     * Gets allow_mobile_payment
     *
     * @return bool
     */
    public function getAllowMobilePayment()
    {
        return $this->container['allow_mobile_payment'];
    }

    /**
     * Sets allow_mobile_payment
     *
     * @param bool $allow_mobile_payment Whether to allow mobile payment
     *
     * @return self
     */
    public function setAllowMobilePayment($allow_mobile_payment)
    {
        if (is_null($allow_mobile_payment)) {
            throw new \InvalidArgumentException('non-nullable allow_mobile_payment cannot be null');
        }
        $this->container['allow_mobile_payment'] = $allow_mobile_payment;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string $currency Currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $allowedValues = $this->getCurrencyAllowableValues();
        if (!in_array($currency, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'currency', must be one of '%s'",
                    $currency,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets expiration_date
     *
     * @return \DateTime|null
     */
    public function getExpirationDate()
    {
        return $this->container['expiration_date'];
    }

    /**
     * Sets expiration_date
     *
     * @param \DateTime|null $expiration_date Expiration date
     *
     * @return self
     */
    public function setExpirationDate($expiration_date)
    {
        if (is_null($expiration_date)) {
            throw new \InvalidArgumentException('non-nullable expiration_date cannot be null');
        }
        $this->container['expiration_date'] = $expiration_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


