<?php
/**
 * CustomerStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Devdraft\Model;
use \Devdraft\ObjectSerializer;

/**
 * CustomerStatus Class Doc Comment
 *
 * @category Class
 * @description Current status of the customer account. Controls access to services and features.
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerStatus
{
    /**
     * Possible values of this enum
     */
    public const ACTIVE = 'ACTIVE';

    public const BLACKLISTED = 'BLACKLISTED';

    public const DEACTIVATED = 'DEACTIVATED';

    public const DELETED = 'DELETED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::BLACKLISTED,
            self::DEACTIVATED,
            self::DELETED
        ];
    }
}


