<?php
/**
 * AllBalancesResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Devdraft\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AllBalancesResponseTest Class Doc Comment
 *
 * @category    Class
 * @description AllBalancesResponse
 * @package     Devdraft
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AllBalancesResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AllBalancesResponse"
     */
    public function testAllBalancesResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "usdc"
     */
    public function testPropertyUsdc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eurc"
     */
    public function testPropertyEurc()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_usd_value"
     */
    public function testPropertyTotalUsdValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
