<?php
/**
 * ProductsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Devdraft\Test\Api;

use \Devdraft\Configuration;
use \Devdraft\ApiException;
use \Devdraft\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productControllerCreate
     *
     * Create a new product.
     *
     */
    public function testProductControllerCreate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productControllerFindAll
     *
     * Get all products.
     *
     */
    public function testProductControllerFindAll()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productControllerFindOne
     *
     * Get a product by ID.
     *
     */
    public function testProductControllerFindOne()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productControllerRemove
     *
     * Delete a product.
     *
     */
    public function testProductControllerRemove()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productControllerUpdate
     *
     * Update a product.
     *
     */
    public function testProductControllerUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productControllerUploadImage
     *
     * Upload images for a product.
     *
     */
    public function testProductControllerUploadImage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
