<?php
/**
 * TestPaymentsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Devdraft AI Payment & Business Management API
 *
 * A comprehensive payment processing and business management API that enables seamless integration of cryptocurrency and traditional payment methods.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Devdraft\Test\Api;

use \Devdraft\Configuration;
use \Devdraft\ApiException;
use \Devdraft\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TestPaymentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Devdraft
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TestPaymentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for testPaymentControllerCreatePaymentV0
     *
     * Process a test payment.
     *
     */
    public function testTestPaymentControllerCreatePaymentV0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testPaymentControllerGetPaymentV0
     *
     * Get payment details by ID.
     *
     */
    public function testTestPaymentControllerGetPaymentV0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for testPaymentControllerRefundPaymentV0
     *
     * Refund a payment.
     *
     */
    public function testTestPaymentControllerRefundPaymentV0()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
